arquivo = open("nome_do_arquivo.txt", "w")
arquivo.write("1982. TRON\n")
arquivo.write("1983, WarGames\n")
arquivo.write("1995, Hackers\n")
arquivo.write("1999, pirates of Silicon Valley\n")
arquivo.write("2010, Teh social Network\n")
arquivo.write("2013, Jobs\n")
arquivo.write("2014, The limitation Game\n")
arquivo.write("2014, Ex Machina\n")
arquivo.write("2016, Snowden\n")
arquivo.write("2018, ready Player One\n")